#bucket_name = "bucket-for-statefile-48693"    # Put the desired GCS Bucket name.
project_name = "rtzen-355308"
region = "us-central1"
zone = "us-central1-a"
vpc_name = "rtzen-uat-vpc"
public_subnet_rang = "172.0.0.0/24"
private_subnet_rang = "172.2.0.0/24"
environment = "rtzen-uat-env"
machine_type = "e2-medium"
